Feat/ignore na
signaux-faibles/predictsignauxfaibles pull request #26
Opened 2021-02-24 18:52 UTC by slebastard

Closes #14 

As a data scientist, I can now customize list IGNORE_NA within config.py, to include any field for which I wish NAs to be ignored, instead of the data entry being dropped. These columns can also be specified as hoc through novel argument cols_ignore_na of Modified SFDataset.prepare_data(), which defaults to config.IGNORE_NA
Logging registers the columns which will be dropped, and those that will be kept upon meeting NAs.

2021-02-25 08:57 UTC, arianelestrade commented
RAS ! tout est bien de mon point de vue et très pertinent pour time_until_outcome !

2021-02-25 08:58 UTC, arianelestrade submitted a review, later dismissed

2021-02-25 09:44 UTC, vviers requested changes
Parfait, merci beaucoup 💯 

Juste les 2/3 changements autour du logging a implémenter et on sera bons :)

2021-02-25 09:44 UTC, vviers commented on lib/data.py
> +        logging.info(
- favorisons les [f-strings](https://realpython.com/python-f-strings/) en python autant que possible, c'est plus lisible !
- je serais plus partisan d'un log par remplacement (ca sera plus facile a lire d'avoir une ligne par remplacement):

```python
for feature, default_value in defaults_map.items():
    logging.debug(f"Column {feature} defaulting to value {default_value}")
```
(on passe le niveau de log a debug car ça pourrait etre très verbeux)

2021-02-25 09:44 UTC, vviers commented on lib/data.py
> +        if cols_ignore_na is None:
a priori, `cols_ignore_na` ne sera jamais `None` ici (tu t'en assures ligne L130 de ton code)

2021-02-25 09:44 UTC, vviers commented on lib/data.py
> +        logging.info(
pareil qu'au dessus:
- f-strings plutot que `.format`
- 1 log par champs
- ~`logging.info`~ --> `logging.debug`

2021-02-26 09:37 UTC, slebastard commented on lib/data.py
> +        if cols_ignore_na is None:
ok si on ne fait pas appel à _remove_na directement

2021-02-26 09:41 UTC, slebastard commented on lib/data.py
> +        logging.info(
Yes ça me paraît effectivement plus lisible, j'ai changé tout ça

2021-02-26 15:49 UTC, vviers commented on lib/data.py
> +    def _remove_na(self, cols_ignore_na):
```suggestion
    def _remove_na(self, cols_ignore_na: list):
```

2021-02-26 15:49 UTC, vviers submitted a review, later dismissed
LGTM 💯 
Merci !

2021-02-26 15:50 UTC, vviers approved these changes

2021-02-26 15:51 UTC, merged