Feat/add doc variables.json
signaux-faibles/predictsignauxfaibles pull request #27
Opened 2021-02-26 17:48 UTC by arianelestrade

Merge request to have access to variable.json comming from opensignauxfaibles. 
It is ignored by gitignore. 
It is documented how to import the json file in README and in Makefile
It is documented how to use it in the notebook -get_started.

2021-02-26 18:51 UTC, vviers requested changes
LGTM sur le fond et pour la commande ! Merci :100:

On discutera Lundi de comment écrire ça comme une commande `make` :)
Bon we !

2021-02-26 18:51 UTC, vviers commented on Makefile
> +cd notebooks
Ça n'est pas exactement comme ça qu'on écrit une commande `make` :)

On en parle Lundi !

2021-02-26 18:51 UTC, vviers commented on Makefile
> +curl --proxy socks5h://localhost:<PORT_INTERNET> -OL https://raw.githubusercontent.com/signaux-faibles/opensignauxfaibles/master/js/reduce.algo2/docs/variables.json -o variables.json
Parfait ✔️

2021-02-26 18:51 UTC, vviers commented on README.md
> +### Optionnel : Pour les personnes qui travaillent sur le serveur labtenant avec un proxy
Je préfèrerais garder cette partie sur Gollum car même si ça n'est pas à proprement parler "touchy" ça ne concerne que ceux qui travaillent sur SF

2021-03-01 10:53 UTC, vviers commented on README.md
> +### Optionnel : Pour les personnes qui travaillent sur le serveur labtenant avec un proxy
@chrnin en fait, je crois que c'est ok de garder ça dans le readme. Tu valides ?
Sinon, je corrige (et nettoierai l'historique)

2021-03-01 10:54 UTC, vviers commented
@arianelestrade qques petites modifs 🙂 

CURL cherche par défaut la variables d'environnement `https_proxy`/`http_proxy`, ce qui évite d'avoir à lui donner manuellement !

2021-03-01 11:32 UTC, arianelestrade commented
Nickel les modifs, par contre, sauf erreur de ma part, le notebook va chercher le .json dans le current directory (cad predictsignauxfaibles/notebooks) alors que les commandes du makefile vont enregistrer ce fichier dans predictsignauxfaibles !

2021-03-01 12:56 UTC, merged